### ISSUE TITLE
Write json to widget

### ISSUE THREAD

**Issue by micio86dev** [LucianoBestia/chext_fill_form_from_json#2]
Hi, I need send a json from my site to your widget (by JavaScript) and use that json in another page. 
Is possibile to do it?
I'm a web developer but I never develop chrome/firefox extensions.

Tnx

**Comment by LucianoBestia** [comment]
Hello,
chrome extension is just javascript+html. 
You can use my code as a template and just change the part where I read the json from local storage
`chrome.storage.local.get('fill_form_json',`
to read the json from your web page.
All together is just 100 lines of code, mostly boilerplate.
